### PR TITLE
Add Bleed support for Cauterizing Flame

### PR DESCRIPTION
**Pull request by teelolws**
Submitted changes from a proper fork, as requested.

### CODE REVIEW

**Comment by teelolws** [comment]
@2072 I think you should string match both "bleed" and "physical".

But really there is no consistency with what debuffs can be dispelled by it. Maybe we could create an adaptation algorithm, one that watches the combat log for successful and unsuccessful dispels? If the player, or another player in the same party/raid successfully dispels a debuff we don't know about using Cauterizing Flame, then we can add its spellId to the list. And same if they fail to dispel it using Cauterizing Flame, we add it to a blacklist?

**Comment by 2072** [comment]
Yes I think that this is possible but you can only see successful dispels I think. (using a remove curse on a poison for example will not create any message because it was never supposed to succeed in the first place).
So it would mean that we'd need to monitor if an active identified bleed debuff is still present after cauterizing flame was used on the unit. This won't be easy because of lags and all of that.

We should test what yields the current implementation before going further, if there are many false positive or not and if new spells are indeed discovered at all.
I'm not sure what Blizzard is using internally to decide if a spell is dispellable using Cauterizing Flame (or other bleed removal gadgets). Is it just a list of spell IDs or what?...

**Comment by teelolws** [comment]
I don't think anyone knows how Blizzard decides what counts as a "Bleed", but the problem has been around for a long time thanks to Stoneform. Despite this, I can't find anything anywhere of anyone ever documenting which debuffs actually count as a bleed.

That list of SpellIDs from my push came from a Weakaura someone wrote for Cauterizing Flame. They were mostly spells that didn't have "bleed" in their description but still counted as a bleed. I think we're going to miss some bleeds but not string searching for "bleed". Heres the first bleed I found searching "bleed" for any spells that don't have "physical": https://www.wowhead.com/spell=381628/internal-bleeding

> [[5 * (18.72% of Attack power)] Bleed damage over 6 sec, based on combo points spent.](https://www.wowhead.com/spell=154904)

**Comment by 2072** [comment]
Ok, thank you for finding this so quickly, I've added support for multiple keywords in the latest alpha and included 'bleed' by default using the global you found.

**Comment by teelolws** [comment]
Looks good. Only potential problem I can foresee is if a player changes their game language, its going to keep the old language values for "bleed" and "physical" in the saved variables, which won't match the spell description anymore. But that should be so niche that players doing this can fix it themselves imo.

**Comment by 2072** [comment]
Good point, this should be fixed in the latest alpha (except for when the user change the default keywords)

**Pull request merged**
